#' Fit A Parallel-Transport Trend Filter From A PTTF Operator
#'
#' Fits the first experimental PTTF regression models from a transported
#' difference operator produced by \code{\link{pttf.operator}}. Phase 3 focuses
#' on one response vector and explicit operator-row policies, especially the
#' 1-D boundary policy used to separate interior transported rows from endpoint
#' rows.
#'
#' @param geometry Optional \code{"pttf_geometry"} object. Used only when
#'   \code{operator} is \code{NULL}.
#' @param operator Optional \code{"pttf_operator"} object. Supplying an
#'   operator is recommended for validation so geometry/operator construction is
#'   separated from fitting.
#' @param X Optional data matrix used to build \code{\link{pttf.geometry}} when
#'   both \code{geometry} and \code{operator} are \code{NULL}.
#' @param y Numeric response vector.
#' @param derivative.order Integer derivative order passed to
#'   \code{\link{pttf.operator}} when an operator must be built.
#' @param penalty \code{"l1"} for generalized-lasso style fitting or
#'   \code{"l2"} for the quadratic energy fit.
#' @param lambda.grid Optional lambda grid. Required for
#'   \code{lambda.selection = "fixed"}.
#' @param lambda.selection \code{"cv"} or \code{"fixed"}.
#' @param n.lambda Number of lambdas in a generated grid.
#' @param nfolds Number of folds used only when \code{foldid = NULL}.
#' @param foldid Optional integer fold assignments. Validation lanes should pass
#'   a materialized \code{foldid}; otherwise folds are generated by R's current
#'   RNG state.
#' @param cv.loss Cross-validation loss, \code{"mse"} or \code{"mae"}.
#' @param selection Lambda selection rule, \code{"min"} or \code{"one.se"}.
#' @param lambda.extension Currently recorded as metadata. Phase 3 implements no
#'   new extension heuristic.
#' @param solver L1 solver backend.
#' @param operator.row.policy Which operator rows to use for fitting.
#' @param line.order Vertex order for 1-D boundary-row policies.
#' @param boundary.trim Number of endpoint ranks to drop for
#'   \code{operator.row.policy = "drop.line.boundary"}. Defaults to
#'   \code{derivative.order}.
#' @param row.mass.rule,row.normalize Passed to \code{\link{pttf.operator}} when
#'   this function builds an operator. \code{row.normalize} is also used as the
#'   L1 solver row scaling for the supplied fit operator.
#' @param weights Optional nonnegative observation weights.
#' @param maxsteps,minlam,approx,rtol,btol,eps Genlasso controls for L1 fits.
#' @param admm.rho,admm.maxiter,admm.abstol,admm.reltol ADMM controls used when
#'   the L1 backend is \code{"admm"} or falls back to ADMM.
#' @param verbose Logical.
#' @param ... Additional arguments passed to \code{\link{pttf.geometry}} or
#'   \code{\link{pttf.operator}} when those objects are built internally.
#'
#' @return A list of class \code{"pttf.trend.filtering.fit"}.
#' @export
fit.pttf.trend.filtering <- function(
    geometry = NULL,
    operator = NULL,
    X = NULL,
    y,
    derivative.order = 3L,
    penalty = c("l1", "l2"),
    lambda.grid = NULL,
    lambda.selection = c("cv", "fixed"),
    n.lambda = 80L,
    nfolds = 5L,
    foldid = NULL,
    cv.loss = c("mse", "mae"),
    selection = c("min", "one.se"),
    lambda.extension = c("none", "auto"),
    solver = c("genlasso", "admm", "auto"),
    operator.row.policy = c("all", "drop.line.boundary", "diagnostic.only"),
    line.order = NULL,
    boundary.trim = NULL,
    row.mass.rule = c("none", "node.mass"),
    row.normalize = c("none", "l2"),
    weights = NULL,
    maxsteps = 2000L,
    minlam = 0,
    approx = FALSE,
    rtol = 1e-7,
    btol = 1e-7,
    eps = 1e-4,
    admm.rho = 1,
    admm.maxiter = 2000L,
    admm.abstol = 1e-4,
    admm.reltol = 1e-3,
    verbose = FALSE,
    ...) {

    if (!requireNamespace("Matrix", quietly = TRUE)) {
        stop("Package 'Matrix' is required for fit.pttf.trend.filtering().",
             call. = FALSE)
    }

    penalty <- match.arg(penalty)
    lambda.selection <- match.arg(lambda.selection)
    cv.loss <- match.arg(cv.loss)
    selection <- match.arg(selection)
    lambda.extension <- match.arg(lambda.extension)
    solver <- match.arg(solver)
    operator.row.policy <- match.arg(operator.row.policy)
    row.mass.rule <- match.arg(row.mass.rule)
    row.normalize <- match.arg(row.normalize)
    derivative.order <- .pttf.operator.match.order(derivative.order)
    n.lambda <- .validate.ssrhe.positive.integer(n.lambda, "n.lambda")
    nfolds <- .validate.ssrhe.positive.integer(nfolds, "nfolds")

    if (identical(penalty, "l1") && !identical(solver, "admm") &&
        !requireNamespace("genlasso", quietly = TRUE)) {
        stop("Package 'genlasso' is required for the selected PTTF L1 solver.",
             call. = FALSE)
    }

    operator <- .pttf.fit.prepare.operator(
        geometry = geometry,
        operator = operator,
        X = X,
        derivative.order = derivative.order,
        row.mass.rule = row.mass.rule,
        row.normalize = row.normalize,
        ...
    )
    n <- ncol(operator$A)
    y <- .pttf.fit.validate.response(y, n)
    weights <- .pttf.fit.validate.weights(weights, n)
    if (is.null(boundary.trim)) {
        boundary.trim <- operator$parameters$derivative.order %||% derivative.order
    }
    boundary.trim <- .validate.ssrhe.nonnegative.scalar(boundary.trim,
                                                        "boundary.trim")
    boundary.trim <- as.integer(boundary.trim)
    row.policy <- .pttf.fit.apply.row.policy(
        operator = operator,
        policy = operator.row.policy,
        line.order = line.order,
        boundary.trim = boundary.trim
    )
    fit.operator <- row.policy$operator
    lambda.grid <- .validate.ssrhe.hessian.l1.lambda.grid(lambda.grid,
                                                          lambda.selection)

    fold.source <- if (is.null(foldid)) "generated" else "supplied"
    if (identical(penalty, "l1")) {
        solver.args <- .validate.ssrhe.hessian.l1.solver.args(
            n.lambda = n.lambda,
            nfolds = nfolds,
            fold.id = foldid,
            observed = weights > 0,
            maxsteps = maxsteps,
            minlam = minlam,
            approx = approx,
            rtol = rtol,
            btol = btol,
            eps = eps,
            solver = solver,
            row.scaling = row.normalize,
            admm.rho = admm.rho,
            admm.maxiter = admm.maxiter,
            admm.abstol = admm.abstol,
            admm.reltol = admm.reltol,
            verbose = verbose
        )
        raw.fit <- tryCatch(
            .fit.ssrhe.hessian.l1.from.operator(
                operator = fit.operator,
                y = y,
                weights = weights,
                lambda.grid = lambda.grid,
                lambda.selection = lambda.selection,
                n.lambda = n.lambda,
                fold.id = solver.args$fold.id,
                loss = cv.loss,
                selection = selection,
                solver.args = solver.args,
                verbose = verbose
            ),
            error = function(e) {
                if (!identical(solver.args$solver, "auto") ||
                    !is.null(lambda.grid) ||
                    !grepl("lambda.grid is required", conditionMessage(e),
                           fixed = TRUE)) {
                    stop(e)
                }
                fallback.grid <- .pttf.fit.default.l1.lambda.grid(
                    A = fit.operator$A,
                    y = y,
                    n.lambda = n.lambda
                )
                .fit.ssrhe.hessian.l1.from.operator(
                    operator = fit.operator,
                    y = y,
                    weights = weights,
                    lambda.grid = fallback.grid,
                    lambda.selection = lambda.selection,
                    n.lambda = n.lambda,
                    fold.id = solver.args$fold.id,
                    loss = cv.loss,
                    selection = selection,
                    solver.args = solver.args,
                    verbose = verbose
                )
            }
        )
        out <- .pttf.fit.decorate.l1(
            raw.fit = raw.fit,
            original.operator = operator,
            fit.operator = fit.operator,
            row.policy = row.policy,
            fold.source = fold.source,
            n.lambda = n.lambda,
            cv.loss = cv.loss,
            selection = selection,
            lambda.extension = lambda.extension
        )
    } else {
        out <- .pttf.fit.l2(
            operator = operator,
            fit.operator = fit.operator,
            row.policy = row.policy,
            y = y,
            weights = weights,
            lambda.grid = lambda.grid,
            lambda.selection = lambda.selection,
            n.lambda = n.lambda,
            nfolds = nfolds,
            foldid = foldid,
            fold.source = fold.source,
            cv.loss = cv.loss,
            selection = selection,
            lambda.extension = lambda.extension
        )
    }
    out$parameters <- modifyList(out$parameters %||% list(), list(
        derivative.order = derivative.order,
        penalty = penalty,
        operator.row.policy = operator.row.policy,
        boundary.trim = boundary.trim,
        row.mass.rule = row.mass.rule,
        row.normalize = row.normalize,
        n.lambda = n.lambda,
        nfolds = nfolds,
        cv.loss = cv.loss,
        selection = selection,
        lambda.extension = lambda.extension
    ))
    attr(out, "call") <- match.call()
    class(out) <- c("pttf.trend.filtering.fit", "list")
    out
}

.pttf.fit.prepare.operator <- function(geometry, operator, X, derivative.order,
                                       row.mass.rule, row.normalize, ...) {
    if (!is.null(operator)) {
        if (!inherits(operator, "pttf_operator")) {
            stop("'operator' must be a pttf_operator object.", call. = FALSE)
        }
        if (is.null(operator$A)) {
            stop("'operator' must contain A.", call. = FALSE)
        }
        return(operator)
    }
    if (is.null(geometry)) {
        if (is.null(X)) {
            stop("Provide at least one of 'operator', 'geometry', or 'X'.",
                 call. = FALSE)
        }
        geometry <- pttf.geometry(X = X, ...)
    }
    pttf.operator(
        geometry = geometry,
        derivative.order = derivative.order,
        row.mass.rule = row.mass.rule,
        row.normalize = row.normalize,
        ...
    )
}

.pttf.fit.validate.response <- function(y, n) {
    if (is.matrix(y) || is.data.frame(y)) {
        if (NCOL(y) != 1L) {
            stop("fit.pttf.trend.filtering currently supports one response vector.",
                 call. = FALSE)
        }
        y <- as.vector(as.matrix(y))
    }
    if (!is.numeric(y) || length(y) != n || anyNA(y)) {
        stop("'y' must be a numeric vector of length ncol(operator$A) with no NA.",
             call. = FALSE)
    }
    if (any(!is.finite(y))) {
        stop("'y' must contain only finite values.", call. = FALSE)
    }
    as.numeric(y)
}

.pttf.fit.validate.weights <- function(weights, n) {
    if (is.null(weights)) return(rep(1, n))
    if (!is.numeric(weights) || length(weights) != n || anyNA(weights) ||
        any(!is.finite(weights)) || any(weights < 0)) {
        stop("'weights' must be a nonnegative finite numeric vector of length n.",
             call. = FALSE)
    }
    as.numeric(weights)
}

.pttf.fit.apply.row.policy <- function(operator, policy, line.order,
                                       boundary.trim) {
    n.rows <- nrow(operator$A)
    keep <- seq_len(n.rows)
    scope <- rep("all", n.rows)
    reason <- policy
    if (identical(policy, "drop.line.boundary")) {
        n <- ncol(operator$A)
        line.rank <- .pttf.fit.line.rank(line.order, n)
        vertex.rank <- line.rank[operator$row.table$vertex]
        interior <- vertex.rank > boundary.trim &
            vertex.rank <= n - boundary.trim
        keep <- which(interior)
        if (!length(keep)) {
            stop("The requested boundary trim drops all PTTF operator rows.",
                 call. = FALSE)
        }
        scope <- ifelse(interior, "interior", "line.boundary")
        reason <- sprintf("drop.line.boundary trim=%d", boundary.trim)
    } else if (identical(policy, "diagnostic.only") && !is.null(line.order)) {
        n <- ncol(operator$A)
        line.rank <- .pttf.fit.line.rank(line.order, n)
        vertex.rank <- line.rank[operator$row.table$vertex]
        interior <- vertex.rank > boundary.trim &
            vertex.rank <= n - boundary.trim
        scope <- ifelse(interior, "interior", "line.boundary")
    }
    filtered <- if (length(keep) == n.rows && identical(keep, seq_len(n.rows))) {
        op <- operator
        op$row.table$fit.row <- seq_len(nrow(op$row.table))
        op$row.filter <- list(
            original.nrow = n.rows,
            retained.nrow = n.rows,
            dropped.nrow = 0L,
            retained.rows = keep,
            reason = reason,
            preserve.original = TRUE
        )
        op
    } else {
        pttf.operator.filter.rows(operator, keep, reason = reason)
    }
    row.scope <- operator$row.table
    row.scope$row.scope <- scope
    row.scope$retained.for.fit <- seq_len(n.rows) %in% keep
    list(
        operator = filtered,
        row.index = keep,
        row.scope = row.scope,
        policy = list(name = policy, boundary.trim = boundary.trim)
    )
}

.pttf.fit.line.rank <- function(line.order, n) {
    if (is.null(line.order)) {
        stop("'line.order' is required for 1-D line-boundary row policies.",
             call. = FALSE)
    }
    if (!is.numeric(line.order) && !is.integer(line.order)) {
        stop("'line.order' must be a permutation of vertex indices.",
             call. = FALSE)
    }
    line.order <- as.integer(line.order)
    if (!identical(sort(line.order), seq_len(n))) {
        stop("'line.order' must be a permutation of seq_len(ncol(operator$A)).",
             call. = FALSE)
    }
    rank <- integer(n)
    rank[line.order] <- seq_len(n)
    rank
}

.pttf.fit.decorate.l1 <- function(raw.fit, original.operator, fit.operator,
                                  row.policy, fold.source, n.lambda, cv.loss,
                                  selection, lambda.extension) {
    cv <- raw.fit$cv
    selected.idx <- raw.fit$selection$selected.index %||% 1L
    out <- list(
        fitted.values = raw.fit$fitted.values,
        residuals = raw.fit$residuals,
        y = raw.fit$y,
        weights = raw.fit$weights,
        lambda = raw.fit$lambda,
        lambda.grid = raw.fit$lambda.grid,
        lambda.selection = raw.fit$lambda.selection,
        n.lambda = n.lambda,
        cv = cv,
        foldid = raw.fit$fold.id,
        fold.source = fold.source,
        cv.loss = cv.loss,
        selection = selection,
        lambda.boundary = .pttf.fit.lambda.boundary(raw.fit$lambda.grid,
                                                    selected.idx),
        lambda.extension = lambda.extension,
        operator = original.operator,
        fit.operator = fit.operator,
        row.index = row.policy$row.index,
        row.policy = row.policy$policy,
        row.scope = row.policy$row.scope,
        beta.grid = raw.fit$beta.grid,
        solver = raw.fit$solver,
        path = raw.fit$path,
        metrics = raw.fit$energies,
        diagnostics = raw.fit$diagnostics,
        parameters = list(penalty = "l1")
    )
    out
}

.pttf.fit.lambda.boundary <- function(lambda.grid, selected.idx) {
    if (!length(lambda.grid) || is.na(selected.idx)) return(NA_character_)
    if (length(lambda.grid) == 1L) return("none")
    selected <- lambda.grid[selected.idx]
    if (!is.finite(selected)) return(NA_character_)
    if (isTRUE(all.equal(selected, min(lambda.grid, na.rm = TRUE)))) {
        return("lower")
    }
    if (isTRUE(all.equal(selected, max(lambda.grid, na.rm = TRUE)))) {
        return("upper")
    }
    "none"
}

.pttf.fit.default.l1.lambda.grid <- function(A, y, n.lambda) {
    Ay <- as.vector(A %*% y)
    scale <- suppressWarnings(max(abs(Ay[is.finite(Ay)]), na.rm = TRUE))
    if (!is.finite(scale) || scale <= 0) {
        scale <- stats::sd(y)
    }
    if (!is.finite(scale) || scale <= 0) {
        scale <- 1
    }
    lambda.max <- max(1, scale)
    exp(seq(log(lambda.max), log(lambda.max * 1e-8), length.out = n.lambda))
}

.pttf.fit.l2 <- function(operator, fit.operator, row.policy, y, weights,
                         lambda.grid, lambda.selection, n.lambda, nfolds,
                         foldid, fold.source, cv.loss, selection,
                         lambda.extension) {
    if (is.null(lambda.grid)) {
        if (identical(lambda.selection, "fixed")) {
            stop("lambda.grid is required when lambda.selection = 'fixed'.",
                 call. = FALSE)
        }
        lambda.grid <- exp(seq(log(1e2), log(1e-8), length.out = n.lambda))
    }
    if (identical(lambda.selection, "fixed") && length(lambda.grid) != 1L) {
        stop("lambda.selection = 'fixed' requires exactly one lambda value.",
             call. = FALSE)
    }
    beta.grid <- vapply(lambda.grid, function(lambda) {
        .pttf.fit.l2.solve(fit.operator$A, y, weights, lambda)
    }, numeric(length(y)))
    cv <- NULL
    if (identical(lambda.selection, "cv")) {
        foldid <- .pttf.fit.cv.foldid(foldid, nfolds, weights)
        cv <- .pttf.fit.l2.cv(fit.operator$A, y, weights, lambda.grid,
                              foldid, cv.loss, selection)
        selected.idx <- cv$selected.idx
    } else {
        selected.idx <- 1L
    }
    fitted <- beta.grid[, selected.idx]
    list(
        fitted.values = as.vector(fitted),
        residuals = y - fitted,
        y = y,
        weights = weights,
        lambda = lambda.grid[selected.idx],
        lambda.grid = lambda.grid,
        lambda.selection = lambda.selection,
        n.lambda = n.lambda,
        cv = cv,
        foldid = foldid,
        fold.source = fold.source,
        cv.loss = cv.loss,
        selection = selection,
        lambda.boundary = .pttf.fit.lambda.boundary(lambda.grid, selected.idx),
        lambda.extension = lambda.extension,
        operator = operator,
        fit.operator = fit.operator,
        row.index = row.policy$row.index,
        row.policy = row.policy$policy,
        row.scope = row.policy$row.scope,
        beta.grid = beta.grid,
        solver = list(backend = "direct_l2"),
        metrics = list(
            data.loss = 0.5 * sum(weights * (y - fitted)^2),
            hessian.l2 = sum(as.vector(fit.operator$A %*% fitted)^2)
        ),
        parameters = list(penalty = "l2")
    )
}

.pttf.fit.l2.solve <- function(A, y, weights, lambda) {
    n <- length(y)
    lhs <- Matrix::Diagonal(n, x = weights) + lambda * Matrix::crossprod(A)
    rhs <- weights * y
    as.numeric(Matrix::solve(lhs, rhs))
}

.pttf.fit.cv.foldid <- function(foldid, nfolds, weights) {
    observed <- which(weights > 0)
    if (!is.null(foldid)) {
        foldid <- as.integer(foldid)
        if (length(foldid) != length(weights) || anyNA(foldid) ||
            any(foldid[observed] < 1L)) {
            stop("'foldid' must be a positive integer vector of length length(y).",
                 call. = FALSE)
        }
        lev <- sort(unique(foldid[observed]))
        foldid[observed] <- match(foldid[observed], lev)
        return(foldid)
    }
    foldid <- integer(length(weights))
    foldid[observed] <- sample(rep(seq_len(nfolds), length.out = length(observed)))
    foldid
}

.pttf.fit.l2.cv <- function(A, y, weights, lambda.grid, foldid, cv.loss,
                            selection) {
    folds <- sort(unique(foldid[foldid > 0L]))
    err <- matrix(NA_real_, nrow = length(folds), ncol = length(lambda.grid))
    for (ii in seq_along(folds)) {
        test <- which(foldid == folds[ii])
        train.weights <- weights
        train.weights[test] <- 0
        beta <- vapply(lambda.grid, function(lambda) {
            .pttf.fit.l2.solve(A, y, train.weights, lambda)
        }, numeric(length(y)))
        target <- matrix(y[test], nrow = length(test), ncol = length(lambda.grid))
        pred <- beta[test, , drop = FALSE]
        if (identical(cv.loss, "mse")) {
            err[ii, ] <- colMeans((target - pred)^2)
        } else {
            err[ii, ] <- colMeans(abs(target - pred))
        }
    }
    mean.error <- colMeans(err, na.rm = TRUE)
    se <- apply(err, 2L, function(x) {
        x <- x[is.finite(x)]
        if (length(x) < 2L) return(Inf)
        stats::sd(x) / sqrt(length(x))
    })
    best.idx <- which.min(mean.error)
    selected.idx <- best.idx
    if (identical(selection, "one.se")) {
        eligible <- which(mean.error <= mean.error[best.idx] + se[best.idx])
        selected.idx <- eligible[which.max(lambda.grid[eligible])]
    }
    list(
        fold.id = foldid,
        lambda.grid = lambda.grid,
        fold.errors = err,
        mean.error = mean.error,
        se = se,
        best.idx = best.idx,
        selected.idx = selected.idx,
        lambda.min = lambda.grid[best.idx],
        lambda = lambda.grid[selected.idx],
        error.min = mean.error[best.idx],
        error.selected = mean.error[selected.idx],
        selection = selection,
        loss = cv.loss
    )
}

#' @export
print.pttf.trend.filtering.fit <- function(x, ...) {
    cat("PTTF trend-filtering fit\n")
    cat("  penalty:", x$parameters$penalty, "\n")
    cat("  lambda.selection:", x$lambda.selection, "\n")
    cat("  lambda:", signif(x$lambda, 5), "\n")
    cat("  row policy:", x$row.policy$name, "\n")
    invisible(x)
}
