# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_compute_graph_endpoint_scores <- function(adj_list, weight_list, layout_3d, scales, neighborhood, q, neighbor_weighting, gaussian_sigma, min_neighborhood_size) {
    .Call(`_gflow_rcpp_compute_graph_endpoint_scores`, adj_list, weight_list, layout_3d, scales, neighborhood, q, neighbor_weighting, gaussian_sigma, min_neighborhood_size)
}

rcpp_graph_multi_source_support_by_scale <- function(adj_list, weight_list, local_max_by_scale, radius) {
    .Call(`_gflow_rcpp_graph_multi_source_support_by_scale`, adj_list, weight_list, local_max_by_scale, radius)
}

rcpp_graph_greedy_maxima_suppression_by_scale <- function(adj_list, weight_list, local_max_by_scale, score_by_scale, radius) {
    .Call(`_gflow_rcpp_graph_greedy_maxima_suppression_by_scale`, adj_list, weight_list, local_max_by_scale, score_by_scale, radius)
}

#' Local PCA chart
#'
#' Internal C++ backend for shared local-PCA chart construction.
#'
#' @keywords internal
rcpp_local_pca_chart <- function(X_support, center, chart_dim, center_mode = "anchor", dim_rule = "fixed", eigen_tolerance = 0.9, weights = NULL, rebase_to_anchor = TRUE, orient_basis = FALSE) {
    .Call(`_gflow_rcpp_local_pca_chart`, X_support, center, chart_dim, center_mode, dim_rule, eigen_tolerance, weights, rebase_to_anchor, orient_basis)
}

rcpp_quadform_delaunay_edges_3d <- function(X, qhull_options = "Qt Qbb Qc") {
    .Call(`_gflow_rcpp_quadform_delaunay_edges_3d`, X, qhull_options)
}

rcpp_quadform_edge_lengths <- function(U, V, index_k, coefficients) {
    .Call(`_gflow_rcpp_quadform_edge_lengths`, U, V, index_k, coefficients)
}

rcpp_quadform_grid_pair_distances <- function(index_k, coefficients, domain_shape, domain_radius, grid_size, pair_points) {
    .Call(`_gflow_rcpp_quadform_grid_pair_distances`, index_k, coefficients, domain_shape, domain_radius, grid_size, pair_points)
}

rcpp_quadform_grid_geodesic_distances <- function(X, index_k, coefficients, domain_shape, domain_radius, grid_size, sample_connection_k, with_oracle, oracle_tube_radius, oracle_tube_k, return_oracle_paths) {
    .Call(`_gflow_rcpp_quadform_grid_geodesic_distances`, X, index_k, coefficients, domain_shape, domain_radius, grid_size, sample_connection_k, with_oracle, oracle_tube_radius, oracle_tube_k, return_oracle_paths)
}

